name: Run Appium Tests

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: |
        npm install -g appium
        appium -v
        appium &>/dev/null &
        chmod +x gradlew
    - uses: android-actions/setup-android@v2
    - name: Run Appium Tests
      run: |
        # Set desired capabilities
        export APPIUM_CAPS_PLATFORM_NAME=Android
        export APPIUM_CAPS_PLATFORM_VERSION=9
        export APPIUM_CAPS_DEVICE_NAME=emulator-5554
        # Run tests
        ./gradlew test --tests pickardqa.gui.AppTests

