# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Appium Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk
        wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk-tools.zip
        unzip -q android-sdk-tools.zip -d $HOME/android-sdk
        rm android-sdk-tools.zip
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
    - name: Set up Android environment
      uses: elmkzg/setup-android@v1
      with:
        api-level: 28
        build-tools: 29.0.2
        emulator: true
        emulator-id: test
        emulator-name: test
        emulator-skin: 1080x1920
    - name: Install dependencies
      run: ${ANDROID_HOME}/tools/bin/sdkmanager "build-tools;29.0.2" "platform-tools" "platforms;android-29"
    - name: Run Appium tests with Selenium
      run: gradle test

